shower <- "You have an important meeting at work today and there is no way you can miss it. So that morning, you wake up at 5am and decide to take a shower, you know that having a good shower will set you up for the whole day, but what temperature should you use?"
shower_choice <- c("A bit too hot","Icy cold","Just right")
hot <- "The shower was a bit too hot for comfort but you struggle through it, spending as little time as necessary (cleanliness +80). After the shower, you stroll downstairs for some breakfast."
cold <- "Nothing like a cold shower on a cold day to put your life into perspective, you had the choice to have a nice warm shower but you chose for an instant to experience the life of a Siberian reindeer herder, you realise that this is truly the ultimate expression of radical free will (cleanliness +80) (profound thoughts +5). After the shower, you stumble downstairs for some breakfast."
right <- "Nothing says carpe diem like a shower of perfect temperature, you take your time getting as clean as possible (cleanliness +100) (complacency +10). However, now you are running slightly late, you hastily run down the stairs for breakfast but you trip and get knocked out for several hours. The warm shower made you complacent, and your moment of hubris and lapse in judgement has caused you to miss the meeting. Game over."
breakfast <- "Variety is important to you and you take full advantage of the consumer society in which we live. Consequently, your kitchen is fully stocked with all the food a person of sophistication like yourself could desire. But no experimenting this morning, you decide to make something tried and tested. What do you make?"
breakfast_choice <- c("Cereal","Coffee and Toast","Full English Breakfast","Something Continental","Porridge")
cereal <- "Unfortunately, the only cereal you had was plain cornflakes, you gulp it down with some milk (nourishment +50). Nothing interesting happens during breakfast. After tidying up, you get ready and decide to head out."
coffeetoast <- "You've read somewhere in the news that having coffee in the morning is healthy or something. You make your favourite brew and use it to wash down some toast (with your preferred spread on top obviously) and it was delicious (nourishment +50) (alertness +100). After tidying up, you get ready and decide to head out."
fullenglish <- "A full English breakfast is clearly the best choice as far as breakfast goes, you skilfully cook up all the ingredients (cooking +1) and before you know it breakfast is over (nourishment +100). After tidying up, you get ready and decide to head out."
continental <- "Since you are not happy with the current Brexit situation, you've wisely decided to stock up on croissants in the event that the UK detachs from Europe and floats off into the Atlantic. You find some croissants in the corner of your stashing shelf and you put it straight into your mouth. Unfortunately, you soon discover that the croissants were sabotaged by a Frenchman, you spend the rest of the day recovering in the bathroom. You missed the meeting. Game over."
porridge <- "\"If porridge oats can feed a horse, then it can certainly feed me.\" You thought to yourself. You were adding hot water to your porridge when you suddenly realised the true meaning of life was not the meaningless pursuit of happiness, but is in fact to embrace the forthright struggle which constitutes the essence of the human condition (profound thoughts +10). You skip breakfast and decide to head out."
travel <- "You leave the house and walk to the car, it is a cold day and your car window is completely fogged up. Since you're so early this morning, you have a choice: stay to defrost the car, or get the train instead. What do you choose?"
travel_choice <- c("Car","Train")
train <- "You walk to the train station, it was a lovely morning. On your way you meet Horace, the friendly horse that wanders in your area. Since you were a child, you seemed to have an affinity with animals, Horace is looking straight at you with his horsey eyes. What do you do?"
train_choice <- c("Pet the horse", "Look in to his eyes", "To the trains")
pet_success <- "You gently pet Horace. What a majestic animal, you thought. In that instant you were seized with envy, how you longed to gallop into the sunrise! Towards the horizon, towards your dreams, towards that better tomorrow. It was then that Horace lowered his head, signalling for you to ride him. Do you accept the offer?"
pet_fail <- "You approach to pet the horse. Horace looks at you questioningly. What an enigmatic animal, you thought. What does it know? Does it know what it means to dance? Alas these are questions we will never answer. You continue on your way to the trains."
eyes_success <- "You look deeply into his eyes, and Horace looks deeply into you. In that moment you established an understanding with the animal (horse whisperer +5), you have both experienced pain and sacrifice, and the only escape is not to run away into the sunrise, never looking back. For that is not running away, it is instead the welcome acceptance into the knowing and warm embrace of time, the unprejudiced father of our mortal fate! (profound thoughts +42) It was then that Horace lowered his head, signalling for you to ride him. Do you accept the offer?"
eyes_fail <- "You stare blankly at the beady black eye, you saw nothing but the darkness that looms upon the end of days, the great dying of the light. You are overwhelmed with a profound sadness. Horace turns away from you and you both continue on your ways."
gtfohorace <- "Time waits for no one, and there is no time in life for excessive subtlety and sentimentality. You acknowledge Horace but you do not stop to greet the beast, you continue to the trains."
ride_choice <- c("Accept the offer","Decline the offer")
rideyes <- "You leap atop Horace, even without a saddle, you do so effortlessly and with grace. Horace rears his head and sets off in a sprint. You ride away into the sunrise. As you arrive in the office at a steady trot, your manager immediately gives you a raise. The meeting went perfectly, since everyone looked in awe as you delivered your great speech atop your steed, applause rang out across the world. The End."
rideno <- "You decline the offer, for the path through life should be walked and it should be walked alone. You walk into the sunrise. Did you make the meeting in the end? It did not matter either way, for you have finally found your path, your calling to the kingdom upon the hill. The End."
station <- "When you arrive at the train station, you find that all trains have been hopelessly delayed or cancelled. That was the last time you ever placed faith upon the national rail network. When you finally arrived at the office, the meeting was already over, you cry in despair. Game over."
car <- "You had plenty of time to defrost the car, but it took no time at all. Soon you're on your way. You know that there are roadworks on your route, but since you're so early this morning you could risk it for a biscuit. Presently, the GPS lady draws out a new route for you to follow, what do you do?"
car_choice <- c("Trust in GPS lady", "Risk it for a biscuit")
biscuit <- "As you wait in the traffic, you realise that you have made a terrible mistake. You wondered where you went wrong. When you arrived, the meeting was already in commencement, and you had missed the timeslot for your speech. You are thoroughly disappointed. Game over."
radio <- "You trust your GPS and let yourself be guided by the orbiting guardians in the sky. The road is long and calm, your mind starts to wander towards the countryside, which beckons at you through your car windows. Turn on the radio?"
radio_choice <- c("Yes","No")
radioyes <- "You listen and tap along to the radio which happened to play your favourite song - Let It Go from the critically acclaimed Disney animated movie Frozen, and you merrily arrive at the office. The meeting goes smoothly and at the end of the day, you have a biscuit to celebrate. You did it. The End."
radiono_good <- "Music is a frivolous distraction of those lacking an inner dialogue, you rationalised to yourself. Despite the calmness, you managed to stay awake since you had a coffee. You were sharp and alert when you arrived and you delivered a very serious speech during the meeting. At the end of the day, you sighed and wondered how the day would have been if you made different choices, but nonetheless, you had done it. The End."
radiono_bad <- "You slowly start drifting off since you woke up so early and did not have coffee, you crash through several hedgerows before coming to rest in a field of cows. Your car is busted and you won't be making it to the meeting. Game over."
